#!/bin/bash

pandoc sig.md \
    --from markdown+implicit_figures \
    --filter pandoc-crossref \
    --filter pandoc-citeproc \
    --number-sections \
    --pdf-engine=lualatex \
    --highlight-style=tango \
    --syntax-definition=./csd_syntaxhighlighting/csound-csd.xml \
    --syntax-definition=./csd_syntaxhighlighting/csound-orc.xml \
    --syntax-definition=./csd_syntaxhighlighting/csound-sco.xml \
    --template template.latex \
    -o "export/sig.pdf"
pdfunite "export/DE_Deckblatt_Digitaler_Upload_2020_Signalverarbeitung.pdf" "export/sig.pdf" "export/FDN & Spectral Processing – eine Projektarbeit im Rahmen der Veranstaltung:
Signalverarbeitung und Audiotechnik.pdf" 
